name: quiz

volumes:
   quiz_api_postgres_data:

services:

  nginx-reverse-proxy:
    container_name: quiz.nginx-reverse-proxy
    image: quiz-nginx-reverse-proxy
    ports:
    - 80:80
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"
  
  keycloak:
    container_name: quiz.auth
    image: quay.io/keycloak/keycloak:26.0.1
    command:
    - start-dev
    - --import-realm
    ports:
    - name: http
      containerPort: 8080
    volumes:
      - ./keycloak/import/:/opt/keycloak/data/import/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: http://LOCALHOST_NAME/auth
      KC_HOSTNAME_ADMIN: http://LOCALHOST_NAME/auth
      #KC_HOSTNAME_DEBUG: true
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_RELATIVE_PATH: /auth/
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      #KC_LOG_LEVEL: DEBUG
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"
    healthcheck:
      test : ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL (args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://LOCALHOST_NAME/auth/health']
      interval: 3s
      timeout: 15s
      retries: 5

  angular-ui:
    container_name: quiz.ui
    image: quiz-ui
    ports:
    - 4200:80
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"

  quiz-db:
    container_name: quiz.api.postgres
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=quiz
    - POSTGRES_PASSWORD=${POSTGRES_QUIZ_PASSWORD}
    - POSTGRES_USER=quiz
    volumes:
    -  quiz_api_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "quiz", "-U", "quiz"]
      interval: 3s
      timeout: 60s
      retries: 20

  quiz-api:
    container_name: quiz.api
    image: quiz-api:0.0.1-SNAPSHOT
    ports:
    - 7084:7084
    environment:
      HOSTNAME: LOCALHOST_NAME
      SERVER_ADDRESS: 0.0.0.0
    depends_on:
      keycloak:
        condition: service_healthy
      quiz-db:
        condition: service_healthy
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"

  bff:
    container_name: quiz.bff
    image: quiz-bff:0.0.1-SNAPSHOT
    ports:
    - 7080:7080
    environment:
      HOSTNAME: LOCALHOST_NAME
      SERVER_ADDRESS: 0.0.0.0
      CLIENT_SECRET: secret
    depends_on:
      keycloak:
        condition: service_healthy
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"
