name: quiz_auth-only

services:

  nginx-reverse-proxy:
    container_name: quiz.auth-only.nginx-reverse-proxy
    image: quiz/nginx-reverse-proxy
    ports:
    - 80:80
    extra_hosts:
    - "host.docker.internal:host-gateway"
  
  keycloak:
    container_name: quiz.auth-only.keycloak
    image: quay.io/keycloak/keycloak:latest
    command:
    - start-dev
    - --import-realm
    ports:
    - 8080:8080
    volumes:
      - ./import/:/opt/keycloak/data/import/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_URL: http://localhost/auth
      KC_HOSTNAME_ADMIN_URL: http://localhost/auth
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      #KC_HOSTNAME_DEBUG: true
      KC_HTTP_RELATIVE_PATH: /auth/
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      #KC_LOG_LEVEL: DEBUG
    extra_hosts:
    - "host.docker.internal:host-gateway"
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost/auth/health/live']
      interval: 5s
      timeout: 5s
      retries: 20
