scheme: http
hostname: localhost
keycloak-host: http://${hostname}/auth
keycloak-realm: quiz
oauth2-issuer: ${keycloak-host}/realms/${keycloak-realm}
oauth2-client-id: quiz-admin
oauth2-client-secret: secret
ui-external-uri: ${scheme}://${hostname}/ui

server:
  port: 7084
  error:
    include-message: always
  shutdown: graceful
  ssl:
    enabled: false

spring:
  config:
    import:
    - optional:configtree:/workspace/config/
    - optional:configtree:/workspace/secret/
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:postgresql://${hostname}:5432/quiz
    username: quiz
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ch4mp@c4-soft.com
    password: change-me
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${oauth2-issuer}
        registration:
          quiz-admin:
            provider: keycloak
            client-id: ${oauth2-client-id}
            client-secret: ${oauth2-client-secret}
            authorization-grant-type: client_credentials
            scope: "openid"

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: ${oauth2-issuer}
          username-claim: preferred_username
          authorities:
          - path: $.realm_access.roles
        resourceserver:
          permit-all:
          - "/users/me"
          - "/quizzes/**"
          - "/actuator/health/readiness"
          - "/actuator/health/liveness"
          - "/v3/api-docs/**"
      rest:
        client:
          keycloak-admin-api:
            base-url: ${keycloak-host}
            authorization:
              oauth2:
                oauth2-registration-id: quiz-admin
        
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: INFO

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:quiz
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
server:
  ssl:
    enabled: true

spring:
  config:
    activate:
      on-profile: ssl

scheme: https