keycloak-host: https://oidc.c4-soft.com
keycloak-realm: quiz
oauth2-issuer: ${keycloak-host}/auth/realms/${keycloak-realm}
ui-uri: https://localhost:8080/ui

server:
  port: 7084
  error:
    include-message: always
  shutdown: graceful
  ssl:
    enabled: false

spring:
  config:
    import:
    - optional:configtree:/workspace/config/
    - optional:configtree:/workspace/secret/
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz
    username: quiz
    password: change-me
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
  cloud:
    openfeign:
      client:
        config:
          keycloak-admin-api:
            url: ${keycloak-host}/auth/admin/realms/${keycloak-realm}
      oauth2:
        enabled: true
        clientRegistrationId: quiz-admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: ch4mp@c4-soft.com
    password: change-me
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${oauth2-issuer}
        registration:
          quiz-admin:
            provider: keycloak
            client-id: quiz-admin
            client-secret: change-me
            authorization-grant-type: client_credentials
            scope:
            - openid
            - offline_access

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: ${oauth2-issuer}
          username-claim: preferred_username
          authorities:
          - path: $.realm_access.roles
        resourceserver:
          permit-all:
          - "/users/me"
          - "/quizzes/**"
          - "/actuator/health/readiness"
          - "/actuator/health/liveness"
          - "/v3/api-docs/**"
        
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: INFO

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:quiz
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

---
server:
  ssl:
    enabled: true

spring:
  config:
    activate:
      on-profile: ssl